### PR TITLE
add unit tests and fixed vtk bug

### PR DESCRIPTION
**Pull request by rouga**
Added unit testing for the SU2MeshParser class :
 + Dimension parser : 1 assertion
 + Interior parser : 11 assertions
 + Nodes parser : 10 assertions
 + BC parser : 16 assertions

Fixed a bug in vtk codes

### CODE REVIEW

**Comment by abraham-bconstant** [comment]
build/test/tests only works if ran from build/test. Is this a something we should define as standard?

**Comment by rouga** [comment]
Maybe a better way of doing this is to create bin/ directory automatically with CMake. In bin/ we can find all the executables, includes "tests"

**Comment by abraham-bconstant** [comment]
We still have to define a directory from which to run the tests executable. Otherwise the relative paths hardcoded in the tests won't work.

**Comment by abraham-bconstant** [comment]
We could make it more robust by using relative paths depending on the working folder using [std::filesystem::path::relative_path](https://en.cppreference.com/w/cpp/filesystem/path) and [std::filesystem::current_path](https://en.cppreference.com/w/cpp/filesystem/current_path)?

**Comment by rouga** [comment]
sounds like a good idea, we can try it

**Pull request merged**
